It is required to implement a python program that simulate a knapsack filling using a greedy algorithm. 

The program should start with a menu to choose from it:
1- The type of Knapsack ( Fractional - I/0)
2- The cost function based on (Maximum Profit - Minimum Weight - Maximum Profit/Weight - All)
3- Update the objects and the maximum weight of the knapsack (constrain)
4- Close the program 

** Always think that this program may be used again with additional functionalities.

** Any additional features may be considered as bonus.

Enjoy Coding

In [61]:
import numpy as np

In [89]:
def main_menu():
    c = input("Enter's' to start Knapsack program or 'q' to exict : ")
    return c


In [90]:
def get_alg_type():
    a= input(f"Enter your choice\n(1) for Greedy alg \n(2) for dynamic programing \n")
    return int(a)

In [91]:
def get_Knapsack_type():
    t = input(f"Enter your choice\n(1) for Fractional Knapsack \n(2) for I/0 Knapsack \n")
    return int(t)

In [92]:
def get_cost_function():
    c = input(f"Enter your choice: \n(1)Maximum Profit \n(2)Minimum Weight \n(3)Maximum Profit/Weight \n(4)All\n")
    return int(c)

In [93]:
def sortitemsperweight(items_weight,items_value):
    for i in range(1,len(items_weight)):
        j=i
        while items_weight[j] > items_weight[j-1] and j > 0:
            items_weight[j] , items_weight[j-1] = items_weight[j-1],items_weight[j]
            items_value[j] , items_value[j-1] = items_value[j-1],items_value[j]
            j=j-1

In [94]:
def sortitemspervalue(items_weight,items_value):
    for i in range(1,len(items_weight)):
        j=i
        while items_value[j] > items_value[j-1] and j > 0:
            items_weight[j] , items_weight[j-1] = items_weight[j-1],items_weight[j]
            items_value[j] , items_value[j-1] = items_value[j-1],items_value[j]
            j=j-1

In [95]:
def get_max_items_weight_values():
    mxweight = int(input("Enter max weight in numbers: "))
    numOfItems = int(input("Enter number of items: "))
    itemsweight = list()
    itemsvalue = list()
    for i in range(numOfItems):
        itemsweight.append(int(input("enter object "+str(i+1)+" weight")))
        itemsvalue.append(int(input("enter object "+str(i+1)+" value")))
    sortitemsperweight(itemsweight,itemsvalue)
    return mxweight, itemsweight, itemsvalue

In [96]:
def F_Knapsack_problem(cost_function,max_weight, itemsWeight, itemsValue):
    if cost_function == 1:
        F_knapsack_maxProfit(max_weight, itemsWeight, itemsValue)
    elif cost_function ==2:
        F_knapsack_minimumWeight(max_weight, itemsWeight, itemsValue)
    elif cost_function ==3:
        F_knapsack_MaximumProfit_Weight(max_weight, itemsWeight, itemsValue)
    elif cost_function ==4:
        F_knapsack_All(max_weight, itemsWeight, itemsValue)
    else:
        print("there is no such type")


In [97]:
def F_knapsack_maxProfit(max_weight, itemsWeight, itemsValue):
    j=max_weight
    item =0
    mxProfit =0
    while j>0 and item<len(itemsWeight) :
        j-=itemsWeight[item]
        mxProfit+=itemsValue[item]
        item+=1
    if j<0 and item<len(itemsWeight):
        mxProfit+=(itemsValue[item]*(-j)//itemsWeight[item]) 
    return mxProfit
    

In [98]:
def F_knapsack_minimumWeight(max_weight, itemsWeight, itemsValue):
    j=max_weight
    item =-1
    mxProfit =0
    while j>0 and item<len(itemsWeight) :
        j-=itemsWeight[item]
        mxProfit+=itemsValue[item]
        item-=1
    if j<0:
        mxProfit+=(itemsValue[item]*(-j)//itemsWeight[item]) 
    return mxProfit

In [99]:
def I_insertion_sort(arr):
    for i in range(1,len(arr)):
        j=i
        while arr[j] < arr[j-1] and j > 0:
            arr[j] , arr[j-1] = arr[j-1],arr[j]
            j=j-1
    return arr 

In [100]:
def F_knapsack_All(max_weight, itemsWeight, itemsValue):
    x=F_knapsack_minimumWeight(max_weight, itemsWeight, itemsValue)
    y = F_knapsack_maxProfit(max_weight, itemsWeight, itemsValue)
    return x,y


In [101]:
def I_knapsack_maxProfit(max_weight, itemsWeight, itemsValue):
    j=max_weight
    item =0
    mxProfit =0
    while j>0 and item<len(itemsWeight) :
        j-=itemsWeight[item]
        mxProfit+=itemsValue[item]
        item+=1
    
    return mxProfit

In [102]:
def I_knapsack_minimumWeight(max_weight, itemsWeight, itemsValue):
    j=max_weight
    item =-1
    mxProfit =0
    while j>0 and item<len(itemsWeight) :
        j-=itemsWeight[item]
        mxProfit+=itemsValue[item]
        item-=1
    
    return mxProfit


In [103]:
def I_Knapsack_problem(cost_function,max_weight, itemsWeight, itemsValue):
    if cost_function == 1:
        I_knapsack_maxProfit(max_weight, itemsWeight, itemsValue)
    elif cost_function ==2:
        I_knapsack_minimumWeight(max_weight, itemsWeight, itemsValue)
    elif cost_function ==3:
        I_knapsack_MaximumProfit_Weight(max_weight, itemsWeight, itemsValue)
    elif cost_function ==4:
        I_knapsack_All(max_weight, itemsWeight, itemsValue)
    else:
        print("there is no such type")


In [104]:
def Knapsack_problem(Knapsack_type,cost_function,max_weight, itemsWeight, itemsValue):
    if Knapsack_type == 1:
        F_Knapsack_problem(cost_function,max_weight, itemsWeight, itemsValue)
    elif Knapsack_type == 2:
        I_Knapsack_problem(cost_function,max_weight, itemsWeight, itemsValue)
    else:
        print("there is no such type")

In [105]:
def I_insertion_sort1(items_weight,items_value):
    for i in range(1,len(items_weight)):
        j=i
        while items_weight[j] < items_weight[j-1] and j > 0:
            items_weight[j] , items_weight[j-1] = items_weight[j-1],items_weight[j]
            items_value[j] , items_value[j-1] = items_value[j-1],items_value[j]
            j=j-1

In [106]:
def max_profit(mx_weight,items_weight,items_value):
    I_insertion_sort1(items_weight,items_value)
    m = np.zeros((len(items_weight)+1,mx_weight+1))
    for i in range(1,len(items_weight)+1):
        for j in range(1,mx_weight+1):
            if items_weight[i-1] > j:
                m[i,j] = m[i-1,j]
            else:
                m[i,j] = max( m[i-1,j] , items_value[i-1] + (m[i-1,j-items_weight[i-1]]) )
    return m

In [108]:
#main program
choice = main_menu()
while choice =='s':
    mxp=0
    max_weight, itemsWeight, itemsValue = get_max_items_weight_values()
    
    Knapsack_type =get_Knapsack_type()
    alg_t = get_alg_type()
    if alg_t == 2 and Knapsack_type==2:
        
        mxp = max_profit(max_weight,itemsWeight,itemsValue)
        print(mxp)
    else:
        cost_function = get_cost_function()
        mxp = Knapsack_problem(Knapsack_type,cost_function,max_weight, itemsWeight, itemsValue)
        print(mxp)
    
    choice = main_menu()
    
print("Knapsack program has been ended")

Enter's' to start Knapsack program or 'q' to exict : s
Enter max weight in numbers: 6
Enter number of items: 2
enter object 1 weight1
enter object 1 value2
enter object 2 weight3
enter object 2 value4
Enter your choice
(1) for Fractional Knapsack 
(2) for I/0 Knapsack 
2
Enter your choice
(1) for Greedy alg 
(2) for dynamic programing 
2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 2. 2. 2.]
 [0. 2. 2. 4. 6. 6. 6.]]
Enter's' to start Knapsack program or 'q' to exict : s
Enter max weight in numbers: 6
Enter number of items: 2
enter object 1 weight1
enter object 1 value2
enter object 2 weight3
enter object 2 value4
Enter your choice
(1) for Fractional Knapsack 
(2) for I/0 Knapsack 
2
Enter your choice
(1) for Greedy alg 
(2) for dynamic programing 
1
Enter your choice: 
(1)Maximum Profit 
(2)Minimum Weight 
(3)Maximum Profit/Weight 
(4)All
1
None
Enter's' to start Knapsack program or 'q' to exict : q
Knapsack program has been ended
